kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdbvolclaim
  namespace: ns-citibike
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
  storageClassName: gp2
